[package]
name = "quamatic/rbx-redux"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exlude = ["tests"]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Promise = "evaera/promise@4.0.0"