return {
	ADD_TODO = "ADD_TODO",
	DISPATCH_IN_MIDDLE = "DISPATCH_IN_MIDDLE",
	GET_STATE_IN_MIDDLE = "GET_STATE_IN_MIDDLE",
	SUBSCRIBE_IN_MIDDLE = "SUBSCRIBE_IN_MIDDLE",
	UNSUBSCRIBE_IN_MIDDLE = "UNSUBSCRIBE_IN_MIDDLE",
	THROW_ERROR = "THROW_ERROR",
	UNKNOWN_ACTION = "UNKNOWN_ACTION",
}
